[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "mirror live number lake engage shove round cart panda pepper gather same easy mass pepper news true poem struggle atom deposit wife palm lawsuit"
